"""initial schema

Revision ID: 77a1a10785c4
Revises: 
Create Date: 2026-07-28 16:59:09.299824

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = '77a1a10785c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='formstatus', native_enum=False, length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_welcome_screen', sa.Boolean(), nullable=False),
    sa.Column('welcome_heading', sa.String(length=255), nullable=False),
    sa.Column('welcome_description', sa.Text(), nullable=False),
    sa.Column('welcome_button_label', sa.String(length=60), nullable=False),
    sa.Column('thank_you_heading', sa.String(length=255), nullable=False),
    sa.Column('thank_you_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_forms_status'), ['status'], unique=False)

    op.create_table('form_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('background_color', sa.String(length=9), nullable=False),
    sa.Column('question_color', sa.String(length=9), nullable=False),
    sa.Column('answer_color', sa.String(length=9), nullable=False),
    sa.Column('button_color', sa.String(length=9), nullable=False),
    sa.Column('button_text_color', sa.String(length=9), nullable=False),
    sa.Column('font_family', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SHORT_TEXT', 'LONG_TEXT', 'MULTIPLE_CHOICE', 'DROPDOWN', 'EMAIL', 'NUMBER', 'YES_NO', 'RATING', name='questiontype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=120), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('allow_decimal', sa.Boolean(), nullable=False),
    sa.Column('rating_max', sa.Integer(), nullable=False),
    sa.Column('rating_icon', sa.String(length=20), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('randomize_options', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_form_id'), ['form_id'], unique=False)
        batch_op.create_index('ix_questions_form_position', ['form_id', 'position'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_is_complete'), ['is_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_token'), ['token'], unique=True)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_answer_per_question')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_response_id'), ['response_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)
        batch_op.create_index('ix_question_options_question_position', ['question_id', 'position'], unique=False)

    op.create_table('answer_options',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['question_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id', 'option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_options')
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index('ix_question_options_question_position')
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_response_id'))
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))

    op.drop_table('answers')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_token'))
        batch_op.drop_index(batch_op.f('ix_responses_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_responses_is_complete'))
        batch_op.drop_index(batch_op.f('ix_responses_form_id'))

    op.drop_table('responses')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_form_position')
        batch_op.drop_index(batch_op.f('ix_questions_form_id'))

    op.drop_table('questions')
    op.drop_table('form_themes')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_status'))
        batch_op.drop_index(batch_op.f('ix_forms_slug'))
        batch_op.drop_index(batch_op.f('ix_forms_owner_id'))

    op.drop_table('forms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
